# Generated by Django 3.1.14 on 2023-07-18 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_auto_20230718_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='appeared_at',
            new_name='appear_at',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='disappeared_at',
            new_name='disappear_at',
        ),
    ]
